#ifndef STATICGROUPS_H
#define STATICGROUPS_H
#include <qpms/groups.h>
extern const qpms_finite_group_t QPMS_FINITE_GROUP_C2;
extern const qpms_finite_group_t QPMS_FINITE_GROUP_C2v;
extern const qpms_finite_group_t QPMS_FINITE_GROUP_trivial_g;
extern const qpms_finite_group_t QPMS_FINITE_GROUP_C4;
extern const qpms_finite_group_t QPMS_FINITE_GROUP_C4v;
extern const qpms_finite_group_t QPMS_FINITE_GROUP_D3h;
extern const qpms_finite_group_t QPMS_FINITE_GROUP_D2h;
extern const qpms_finite_group_t QPMS_FINITE_GROUP_D4h;
extern const qpms_finite_group_t QPMS_FINITE_GROUP_x_and_z_flip;
extern const qpms_finite_group_t QPMS_FINITE_GROUP_y_and_z_flip;
#endif
