#ifndef SYMMETRIES_H
#define SYMMETRIES_H
/* TODO.
 *
 * Here will be functions providing point group operations
 * operating on translation operators and T-matrices
 * as in tmatrices.py.
 * 
 * At least I want:
 * - Wigner D matrices
 * - Basic mirror operations for T-matrices
 * - Inversion operation for the translation matrices
 *
 * Maybe (much later) also point and space group irrep 
 * functionality as in symmetries.py.
 * However, I think that the group structures can be simply
 * hard-coded/generated by a python script, then there is 
 * no need to check the group consistency etc. at runtime.
 *
 * 
 */

#endif // SYMMETRIES_H
